name: Deploy

on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 22.7.0
          cache: 'pnpm'

      - name: Build 1
        run: |
          corepack enable
          pnpm install --production
          npm run build

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: dist
          git-config-name: "GitHub Actions"
          git-config-email: "actions@github.com"
